### ISSUE TITLE
Doesn't build

### ISSUE THREAD

**Issue by Panadero1** [winstonbullen/DuoCode#72]
Hello, can you help me figure out why this isn't building (I am your reviewer)

I download the repository, with node > v18 installed
I run make install (no issues)
I run make build (no issues)
I run make run:
```
DuoCode/backend/node_modules/mongodb-connection-string-url/lib/index.js:9
    return (connectionString.startsWith('mongodb://') ||
                             ^

TypeError: Cannot read properties of undefined (reading 'startsWith')
    at connectionStringHasValidScheme (DuoCode/backend/node_modules/mongodb-connection-string-url/lib/index.js:9:30)
    at new ConnectionString (DuoCode/backend/node_modules/mongodb-connection-string-url/lib/index.js:85:34)
    at parseOptions (DuoCode/backend/node_modules/mongodb/lib/connection_string.js:191:17)
    at new MongoClient (DuoCode/backend/node_modules/mongodb/lib/mongo_client.js:48:63)
    at DuoCode/backend/dist/src/usersdb.js:48:18
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)

Node.js v19.9.0
make: *** [Makefile:16: run] Error 1
```

I am running on a Manjaro Linux distribution on a x86-64 architecture. I can provide more details if needed

**Comment by winstonbullen** [comment]
I do not believe you have followed all of the setup instructions. Please contact us on Slack for the `.env` file necessary to develop locally.

**Comment by Panadero1** [comment]
I see. I'll do that

**Comment by winstonbullen** [comment]
Cool. Closing this issue in that case.
